export default {
    size: '1.8em', // default <Icon> size applied
    class: 'icon', // default <Icon> class applied
    mode: 'css', // default <Icon> mode applied
    aliases: {
        'account': 'material-symbols:account-circle',
        'activity': 'material-symbols:person-play-outline-rounded',
        'addImage': 'material-symbols:add-photo-alternate-outline',
        'appSettings': 'tabler:device-desktop-cog',
        'article': 'material-symbols:article-outline-rounded',
        'attributes': 'material-symbols:user-attributes-outline-rounded',
        'back': 'material-symbols:arrow-back-rounded',
        'book': 'material-symbols:menu-book-outline-rounded',
        'cameraBack': 'material-symbols:photo-camera-back-outline-rounded',
        'cameraFront': 'material-symbols:photo-camera-front-outline-rounded',
        'chat': 'material-symbols:chat-rounded',
        'checkCircle': 'material-symbols:check-circle-outline-rounded',
        'close': 'material-symbols:close',
        'coffee': 'material-symbols:coffee',
        'cog': 'ic:round-settings',
        'content': 'material-symbols:deployed-code-outline-sharp',
        'cookieSettings': 'mdi:cookie-cog-outline',
        'crop': 'material-symbols:frame-person-outline-rounded',
        'delete': 'material-symbols:delete-outline-rounded',
        'device': 'material-symbols:devices-outline',
        'edit': 'material-symbols:edit',
        'email': 'material-symbols:alternate-email',
        'error': 'bx:error-alt0',
        'forest': 'material-symbols:forest-outline',
        'fullScreen': 'material-symbols:fullscreen-rounded',
        'fullScreenExit': 'material-symbols:fullscreen-exit-rounded',
        'heartEmpty': 'solar:heart-outline',
        'heartFull': 'solar:heart-bold',
        'home': 'material-symbols:other-houses',
        'info': 'material-symbols:info-outline',
        'loading': 'svg-spinners:12-dots-scale-rotate',
        'lockClosed': 'material-symbols:lock-outline',
        'logout': 'material-symbols:logout',
        'manageAccount': 'ic:sharp-manage-accounts',
        'menu': 'material-symbols:menu-rounded',
        'notVisible': 'material-symbols:visibility-off-outline-rounded',
        'openInNew': 'material-symbols:open-in-new',
        'personAdd': 'material-symbols:person-add',
        'personAddDisabled': 'material-symbols:person-add-disabled',
        'personAlert': 'material-symbols:person-alert-outline-rounded',
        'personCancel': 'material-symbols:person-cancel-outline',
        'personCheck': 'material-symbols:person-check',
        'plus': 'material-symbols:add',
        'send': 'material-symbols:send-rounded',
        'success': 'icon-park-outline:success',
        'tip': 'material-symbols:tips-and-updates-outline-rounded',
        'unchecked': 'mdi:checkbox-blank-outline',
        'checked': 'mdi:checkbox-marked-outline',
        'visible': 'material-symbols:visibility-outline-rounded',
        'warning': 'bx:error',
        'zoomIn': 'material-symbols:zoom-in',
        'zoomOut': 'material-symbols:zoom-out'
      }
}